---
title: "Code Book"
author: "Max Guthier"
date: "July 26, 2015"
output: html_document
---

## Data Source

The data in this exercise was collected from the accelerometers from the Samsung Galaxy S smartphone The documentation of the experiments is available from the project website (http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones), the raw data itself was obtained from this repository on July 21st, 2015:
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 


## Data Set Information (quoted from the original experimenters)

"The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 
The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain."


## Variable Information

### Activity
A six-level factor variable with the type of activity performed by the subject during the respective measurement.
1. Walking
2. Walking Upstairs
3. Walking Downstairs
4. Sitting
5. Standing
6. Laying

### Subject
A thirty-level variable with the ID number of the subjects performing the activity during the respective measurement. Note that beyond their unique identifiers, no metadata about the individual test subjects is known.

### Acceleration("Acc") & Velocity("Gyro") Variables
From the 561 variables of the original data source, only variables identifying the "mean" (including "mean frequency") or "standard deviation" of an acceleration or velocity attribute were included in the tidy data set. The 79 variables are:

*tBodyAcc (6 variables)
  mean and standard deviation for X,Y,Z axxes
*tGravityAcc (6 variables)
  mean and standard deviation for X,Y,Z axxes
*tBodyAccJerk (6 variables)
  mean and standard deviation for X,Y,Z axxes
*tBodyGyro (6 variables)
  mean and standard deviation for X,Y,Z axxes
*tBodyGyroJerk (6 variables)
  mean and standard deviation for X,Y,Z axxes
*tBodyAccMag (2 variables)
  mean and standard deviation
*tBodyAccJerkMag (2 variables)
  mean and standard deviation
*tBodyGyroMag (2 variables)
  mean and standard deviation
*fBodyAcc (9 variables)
  mean, mean frequency and standard deviation for X,Y,Z axxes
*fBodyAccJerk (9 variables)
  mean, mean frequency and standard deviation for X,Y,Z axxes
*fBodyGyro (9 variables)
  mean, mean frequency and standard deviation for X,Y,Z axxes
*fBodyAccMag (3 variables)
  mean, mean frequency and standard deviation
*fBodyBodyAccJerkMag (3 variables)
  mean, mean frequency and standard deviation
*fBodyBodyGyroMag (3 variables)
  mean, mean frequency and standard deviation
*fBodyBodyGyroJerkMag (3 variables)
  mean, mean frequency and standard deviation


## Citation Request

The following citation should be added to each publication that makes use of the raw data set or any processed version of it (such as the tidy data set in this repository).

Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. A Public Domain Dataset for Human Activity Recognition Using Smartphones. 21th European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning, ESANN 2013. Bruges, Belgium 24-26 April 2013.